services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - '.env'
  app:
    build:
      .
    ports:
      - "8080:8080"
    env_file:
      - '.env'
    command:
      - "uvicorn app.main:app --host=${HOST} --port=${PORT}"
