services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - ./redis:/data
    env_file:
      - .env
  flower:
    build: .
    command: "celery -A app.tasks.celery_app flower --basic-auth=${FLOWER_USER}:${FLOWER_PASSWORD}"
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - .env
  scraper:
    build: .
    command: "celery -A app.tasks.celery_app worker -n server_worker --loglevel=INFO -Q celery"
  beat:
    build: .
    command: "celery -A app.tasks.celery_app beat --loglevel=DEBUG"
